# Configura��o do Banco MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/workshopmysql
spring.datasource.username=root
spring.datasource.password=Kranio47!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA e Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true